---
- name: Create journal config directory
  file:
    path: /etc/systemd/journald.conf.d
    state: directory
  tags:
    - sudoforge.journald

- name: Push journal max size config
  template:
    src: 00-journal-size.conf.j2
    dest: /etc/systemd/journald.conf.d/00-journal-size.conf
  tags:
    - sudoforge.journald
