---
- name: Install wpa_supplicant
  package:
    name: wpa_supplicant
    state: present
  tags:
    - sudoforge.wpa_supplicant

- include_tasks: iter.yml
  loop: "{{ sudoforge_wpa_supplicant_configs }}"
  tags:
    - sudoforge.wpa_supplicant
