---
galaxy_info:
  author: sudoforge
  description: >
    install and configure wpa supplicant
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: ArchLinux
      versions:
        - all
  tags:
    - network
    - supplicant
    - wpa
dependencies : []
