---
- name: Remove netctl
  pacman: name=netctl state=absent

- name: Push wired network configuration file
  copy:
    src: 20-wired.network
    dest: /etc/systemd/network/20-wired.network
    mode: 0644
  notify: restart network services

- name: Push wireless network configuration file
  copy:
    src: 25-wireless.network
    dest: /etc/systemd/network/25-wireless.network
    mode: 0644
  notify: restart network services

- name: Create symlink to systemd's resolvconf at /etc/resolv.conf
  file:
    force: yes
    path: /etc/resolv.conf
    state: link
    src: /run/systemd/resolved/stub-resolv.conf

- name: Enable network services
  systemd: name={{ item }} enabled=yes
  with_items:
    - systemd-networkd.service
    - systemd-resolved.service
