---
# nameservers to use, in order of preference
sudoforge_unbound_nameservers:
  - 1.1.1.1     # Cloudflare DNS over HTTPS
  - 1.0.0.1     # Cloudflare DNS over HTTPS
  - 8.8.8.8     # Google
  - 209.244.0.3 # Level 3
  - 74.82.42.42 # Hurricane Electric

# how often to update the root name server list
sudoforge_unbound_roothints_timer: monthly

# verbosity number, 0 is least verbose
sudoforge_unbound_verbosity: 1

# print statistics to the log every N seconds
# "" or 0 to disable
sudoforge_unbound_statistics_interval: 0

# enable shm for stats
sudoforge_unbound_shm_enable: "no"

# this key is used for shm, and n+1 for shared mem segment
sudoforge_unbound_shm_key: 11777

# enable cumulative statistics, without clearing them after printing
sudoforge_unbound_statistics_cumulative: "no"

# enable extended statistics
sudoforge_unbound_extended_statistics: "no"

# number of threads to create, 1 disables threading
sudoforge_unbound_num_threads: 1
