---
- name: Apply template for /etc/hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    mode: 0644
  when:
    - hostname.enabled == true
  tags:
    - notest
    - sudoforge.hostname

- name: Remove default comments from /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: absent
  with_items:
    - "# Static table lookup for hostnames."
    - "# See hosts(5) for details."
  when:
    - hostname.enabled == true
  tags:
    - notest
    - sudoforge.hostname

- name: Generate a merged list of hostnames
  set_fact:
    merged_hostname_entries:
      - "localhost"
      - "{{ hostname.name }}"
  when:
    - hostname.enabled == true
  tags:
    - sudoforge.hostname

- name: Merge aliases into the generated list
  set_fact:
    merged_hostname_entries: "{{ merged_hostname_entries + hostname.aliases | unique | sort() }}"
  when:
    - hostname.enabled == true
  tags:
    - sudoforge.hostname

- name: Remove undefined 127.0.0.1 assignments from /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "127.0.0.1 (?!{{ merged_hostname_entries | unique | sort() | join('|') }})"
    state: absent
  when:
    - hostname.enabled == true
  tags:
    - notest
    - sudoforge.hostname

- name: Add hostname entries to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ item }}"
    insertbefore: BOF
    state: present
  with_items: "{{ merged_hostname_entries | unique | sort() }}"
  when:
    - hostname.enabled == true
  tags:
    - notest
    - sudoforge.hostname
