---
.test:
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker info
    - pip install pipenv
    - pipenv shell
    - pipenv sync --dev
  script:
    - make test

test:python3.7:
  image: python:3.7
  extends: .test

test:python3.6:
  image: python:3.6
  extends: .test
