---
.test:
  services:
    - docker:dind
  script:
    - pip install pipenv
    - pipenv install --system
    - make test

test:python3.7:
  image: python:3.7
  extends: .test

test:python3.6:
  image: python:3.6
  extends: .test
