---
.test:
  services:
    - docker:stable-dind
  script:
    - pip install pipenv
    - pipenv run pip install pip==18.0
    - pipenv install
    - make test

test:python3.7:
  image: python:3.7
  extends: .test

test:python3.6:
  image: python:3.6
  extends: .test

test:python2.7:
  image: python:2.7
  extends: .test
