---
.test:
  variables:
    DOCKER_VERSION: 18.06.1
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:stable-dind
  before_script:
    - cat /etc/hosts
    - curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}-ce.tgz
    - tar xzvf docker-${DOCKER_VERSION}-ce.tgz --strip 1 -C /usr/local/bin docker/docker
    - rm docker-${DOCKER_VERSION}-ce.tgz
    - docker info
    - pip install pipenv
    - pipenv install --system
  script:
    - make test

test:python3.7:
  image: python:3.7
  extends: .test

test:python3.6:
  image: python:3.6
  extends: .test
