---
- name: Create unique list of groups
  set_fact:
    merged_group_list: "{{ merged_group_list|default([]) + [item.primary_group | default(item.username)] + (item.groups | default([])) | unique | sort }}"
  loop: "{{ sudoforge_user.users }}"
  when:
    - sudoforge_user.users is defined
  tags:
    - sudoforge.user

- name: Create groups from merged list
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ merged_group_list }}"
  when:
    - sudoforge_user.users is defined
  tags:
    - sudoforge.user

- include_tasks: user.yml
  loop: "{{ sudoforge_user.users }}"
  loop_control:
    loop_var: user
  when:
    - sudoforge_user.users is defined
  tags:
    - sudoforge.user
