---
- name: install packages
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - aircrack-ng
    - arp-scan
    - openvpn
    - mtr
    - net-tools
    - bind-tools
    - whois
    - nmap
    - tcpdump
    - sshuttle
    - wireshark-cli
    - socat
    - nethogs
    - speedtest-cli
  tags:
    - sudoforge.nettools
