---
pacman_packages: []
pacman_repositories:
  - name: core
    priority: "01"
    options:
      - Include = /etc/pacman.d/mirrorlist
  - name: extra
    priority: "02"
    options:
      - Include = /etc/pacman.d/mirrorlist
  - name: community
    priority: "03"
    options:
      - Include = /etc/pacman.d/mirrorlist
pacman_options:
  - HoldPkg = pacman glibc
  - Architecture = auto
  - CheckSpace
  - SigLevel = Required DatabaseOptional
  - LocalFileSigLevel = Optional
