---
- name: install packages
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - autocutsel
    - autorandr
    - sxhkd
    - xautomation
    - xdg-user-dirs
    - xf86-input-libinput
    - xorg-server
    - xorg-sessreg
    - xorg-xdpyinfo
    - xorg-xev
    - xorg-xinit
    - xorg-xmodmap
  tags:
    - sudoforge.x

- name: install video driver(s)
  pacman:
    name: "{{ xorg_video_drivers }}"
    state: present
  tags:
    - sudoforge.x

- name: Create XDG user directories
  command: /usr/bin/xdg-user-dirs-update
  become: yes
  become_user: "{{ item.username }}"
  loop: "{{ sudoforge_user.users }}"
  tags:
    - xdg
    - sudoforge.x
