---
- name: Install hostsctl
  aur:
    name: hostsctl
    dbpath: "{{ sudoforge_aur_db_path }}"
  become: "yes"
  become_user: "{{ sudoforge_aur_user }}"
  tags:
    - sudoforge.hostsctl

- name: Push hostsctl config
  template:
    src: hostsctl.conf.j2
    dest: /etc/hostsctl.conf
  register: hostsctlconf
  tags:
    - sudoforge.hostsctl

- name: Update hostsctl
  command: hostsctl update
  when: hostsctlconf.changed
  tags:
    - sudoforge.hostsctl

- name: copy service file hostsctl.service
  copy:
    src: hostsctl.service
    dest: /etc/systemd/system/hostsctl.service
  tags:
    - sudoforge.hostsctl

- name: apply template for /etc/systemd/system/hostsctl.timer
  template:
    src: hostsctl.timer.j2
    dest: /etc/systemd/system/hostsctl.timer
  register: hostsctltimer
  tags:
    - sudoforge.hostsctl

- name: enable timer /etc/systemd/system/hostsctl.timer
  systemd:
    name: hostsctl.timer
    enabled: "{{ 'yes' if sudoforge_hostsctl_timer_enabled == true else 'no' }}"
    state: "{{ 'started' if sudoforge_hostsctl_timer_enabled == true else 'stopped' }}"
    daemon_reload: "{{ 'yes' if hostsctltimer.changed or hostsctlconf.changed else 'no' }}"
  tags:
    - sudoforge.hostsctl
