---
- name: Install hostsctl
  aur:
    name: hostsctl
    user: "{{ sudoforge_aur_user }}"
    dbpath: "{{ sudoforge_aur_db_path }}"
  tags:
    - sudoforge.aur

- name: Push hostsctl config
  template:
    src: hostsctl.conf.j2
    dest: /etc/hostsctl.conf
  tags:
    - sudoforge.aur

- name: Update hostsctl
  command: hostsctl update
  tags:
    - sudoforge.aur
