---
- name: Create system directory for background images
  file:
    path: "{{ sudoforge_background_directory }}"
    state: directory
    mode: 0755
  tags:
    - sudoforge.background

- name: Download user-defined background images
  get_url:
    url: "{{ item.url }}"
    dest: "{{ sudoforge_background_directory }}/{{ item.name }}"
    backup: "yes"
    checksum: "{{ item.checksum }}"
    mode: 0644
  with_items:
    - "{{ sudoforge_background_images }}"
  tags:
    - sudoforge.background
