---
- name: "check for key: {{ item }}"
  command: gpg --list-key "{{ item }}"
  register: pgp_key_check
  ignore_errors: yes
  changed_when: False
  tags:
    - sudoforge.aur

- name: "download gpg signing key: {{ item }}"
  command: gpg --recv-key "{{ item }}"
  when:
    - pgp_key_check.failed == True
  tags:
    - sudoforge.aur
