---
- block:
    - name: "install aur gpg keys"
      include_tasks: gpg.yml
      loop: "{{ sudoforge_aur_gpg_keys }}"
  become: "yes"
  become_user: "{{ sudoforge_aur_user }}"
  tags:
    - sudoforge.aur

- name: create and add packages to local repository
  aur:
    name: "{{ item }}"
    user: "{{ sudoforge_aur_user }}"
    dbpath: "{{ sudoforge_aur_db_path }}"
  loop: "{{ sudoforge_aur_packages }}"
  tags:
    - sudoforge.aur
