---
- name: create and add packages to local repository
  aur:
    name: "{{ item }}"
    user: "{{ aur_user }}"
    dbpath: "{{ aur_db_path }}"
  loop: "{{ aur_packages }}"
  tags:
    - sudoforge.aur
