---
galaxy_info:
  author: sudoforge
  description: >
    install and configure sudo
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: ArchLinux
      versions:
        - all
  tags:
    - sudo
    - wheel
dependencies:
  - user
