---
galaxy_info:
  author: sudoforge
  description: >
    install and configure openssh + sshd
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: ArchLinux
      versions:
        - all
  tags: []
dependencies: []
