---
- name: Install mkinitcpio
  pacman:
    name: mkinitcpio
    state: present
  when:
    - initramfs.enabled == true
  tags:
    - sudoforge.initramfs

- name: Install supplementary packages
  pacman:
    name: "{{ initramfs.packages }}"
    state: present
  when:
    - initramfs.enabled == true
    - initramfs.packages | length
  tags:
    - sudoforge.initramfs

- name: Apply template for /etc/mkinitcpio.conf
  template:
    src: mkinitcpio.conf.j2
    dest: /etc/mkinitcpio.conf
    mode: 0644
  notify: generate initramfs image
  when:
    - initramfs.enabled == true
  tags:
    - notest
    - sudoforge.initramfs
