---
# A list of objects describing the networkd profiles
sudoforge_networkd_profiles:
  - name: wired
    priority: 20
    config:
      Match:
        - Name=en*
      Network:
        - DHCP=yes
      DHCP:
        - RouteMetric=10

# Whether or not to enable the systemd-networkd-wait-online.service unit. On
# machines with non-persistent network connectivity (e.g. laptops), enabling
# this unit can cause additional wait times when booting up (in the order of
# minutes depending on the number of interfaces you have).
#
# It is also possible to limit the interfaces to wait for, if you need them [1].
# At this time, this operation is not supported by this role.
#
# [1]: https://www.man7.org/linux/man-pages//man8/systemd-networkd-wait-online.8.html
sudoforge_systemd_networkd_wait_online: False
