---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: archer
    image: terencewestphal/archlinux:latest
    pull: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp:unconfined
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    skip-tags: notest
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: yamllint
