---
- name: Install hostapd
  pacman:
    name: hostapd
    state: present
  when:
    - hostapd is defined
    - hostapd.enabled == true
  tags:
    - chroot

- name: Apply template for /etc/hostapd/hostapd.conf
  template:
    src: hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
    mode: 0644
  when:
    - hostapd is defined
    - hostapd.enabled == true
  tags:
    - chroot

- name: Start the service unit hostapd.service
  systemd:
    name: hostapd.service
    state: started
  when:
    - hostapd is defined
    - hostapd.enabled == true
    - hostapd.service is defined
    - hostapd.service.started == true
  tags:
    - chroot

- name: Enable the service unit hostapd.service
  systemd:
    name: hostapd.service
    enabled: yes
  when:
    - hostapd is defined
    - hostapd.enabled == true
    - hostapd.service is defined
    - hostapd.service.enabled == true
  tags:
    - chroot
