---
galaxy_info:
  author: sudoforge
  description: >
    install zsh and plugins
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - shell
    - zsh
dependencies: []
