---
- name: Check /etc/adjtime
  stat: path=/etc/adjtime
  when:
    - timezone.enabled == true
  register: adjtime
  tags:
    - notest
    - sudoforge.timezone

- name: Generate /etc/adjtime
  command: hwclock --systohc
  when:
    - timezone.enabled == true
    - timezone.hwclock == 'UTC' and adjtime.stat.exists == false
  tags:
    - notest
    - sudoforge.timezone

- name: manually link /etc/localtime to the specified timezone
  file:
    force: "yes"
    state: link
    path: /etc/localtime
    src: /usr/share/zoneinfo/{{ timezone.zoneinfo }}
  when:
    - timezone.enabled == true
    - sudoforge_timezone_update_enabled == false
  tags:
    - sudoforge.timezone

- name: install localtime-git
  aur:
    name: localtime-git
    dbpath: "{{ sudoforge_aur_db_path }}"
  become: "yes"
  become_user: "{{ sudoforge_aur_user }}"
  when:
    - timezone.enabled == true
    - sudoforge_timezone_auto_update == true
  tags:
    - sudoforge.timezone

- name: enable localtime.service
  systemd:
    name: localtime.service
    enabled: "{{ 'yes' if sudoforge_timezone_auto_update == true else 'no' }}"
    state: "{{ 'started' if sudoforge_timezone_auto_update == true else 'stopped' }}"
  when:
    - timezone.enabled == true
  tags:
    - sudoforge.timezone
