---
- name: Set the timezone
  file:
    force: yes
    path: /etc/localtime
    state: link
    src: /usr/share/zoneinfo/{{ timezone.region }}/{{ timezone.city }}

- name: Generate /etc/adjtime
  command: hwclock --systohc
