---
- name: Set the time zone
  file:
    force: "yes"
    state: link
    path: /etc/localtime
    src: /usr/share/zoneinfo/{{ timezone.zoneinfo }}
  tags:
    - sudoforge.timezone

- name: Check /etc/adjtime
  stat: path=/etc/adjtime
  register: adjtime
  tags:
    - notest
    - sudoforge.timezone

- name: Generate /etc/adjtime
  command: hwclock --systohc
  when:
    - timezone.enabled == true
    - timezone.hwclock == 'UTC' and adjtime.stat.exists == false
  tags:
    - notest
    - sudoforge.timezone
