---
- name: Set the time zone
  file:
    force: "yes"
    state: link
    path: /etc/localtime
    src: /usr/share/zoneinfo/{{ timezone.zoneinfo }}
  tags:
    - chroot

- name: Check /etc/adjtime
  stat: path=/etc/adjtime
  register: adjtime
  tags:
    - chroot
    - notest

- name: Generate /etc/adjtime
  command: hwclock --systohc
  when: timezone.hwclock == 'UTC' and adjtime.stat.exists == false
  tags:
    - chroot
    - notest
