---
galaxy_info:
  author: sudoforge
  description: >
    {{ cookiecutter.description }}
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: ArchLinux
      versions:
        - all
  {%- if not cookiecutter.tags | length %}
  tags: []
  {%- else %}
  tags:
    {%- for tag in cookiecutter.tags.split() | unique | sort(case_sensitive=False) %}
    - {{ tag }}
    {%- endfor %}
  {%- endif %}
{%- if not cookiecutter.dependencies | length %}
dependencies : []
{%- else %}
dependencies:
{%- for dep in cookiecutter.dependencies.split() | unique | sort(case_sensitive=False) %}
  - {{ dep }}
{%- endfor %}
{%- endif %}
