---
galaxy_info:
  author: sudoforge
  description: >
    install cronie and start+enable the service
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: ArchLinux
      versions:
        - all
  tags:
    - cron
    - cronie
dependencies : []
