---
- name: "check for existence of {{ item }}"
  shell: systemctl list-unit-files "{{ item }}" | grep "{{ item }}"
  register: unit_file_check
  ignore_errors: yes
  changed_when: False
  tags:
    - sudoforge.networkd

- name: "disable and stop {{ item }}"
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  when:
    - unit_file_check.failed == false
  tags:
    - sudoforge.networkd
