---
- include_tasks: disable_service.yml
  loop:
    - netctl.service
    - NetworkManager.service
  tags:
    - sudoforge.networkd

- name: Apply the interface configuration template
  template:
    src: network.j2
    dest: "/etc/systemd/network/{{ item.priority }}-{{ item.name }}.network"
    mode: 0644
  notify: restart systemd network services
  loop: "{{ sudoforge_networkd_profiles }}"
  tags:
    - sudoforge.networkd

- name: Enable and start systemd-networkd.service
  systemd:
    name: systemd-networkd.service
    enabled: yes
    state: started
  tags:
    - sudoforge.networkd
