---
- name: install openssh
  package:
    name: openssh
    state: present
  tags:
    - sudoforge.sshd

- name: apply template for /etc/ssh/sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  tags:
    - sudoforge.sshd

- name: create openssh systemd unit file directory
  file:
    path: /etc/systemd/system/sshd.socket.d
    state: directory
  tags:
    - sudoforge.sshd

- name: apply template for /etc/systemd/system/sshd.socket.d/override.conf
  template:
    src: sshd-socket-override.conf.j2
    dest: /etc/systemd/system/sshd.socket.d/override.conf
  notify:
    - reload systemd config
    - restart sshd
  tags:
    - sudoforge.sshd

- name: manage sshd.socket service
  service:
    name: sshd.socket
    enabled: "{{ 'yes' if sshd_service_enabled == true else 'no' }}"
    state: "{{ 'started' if sshd_service_enabled == true else 'stopped' }}"
  tags:
    - sudoforge.sshd
