---
- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - freetype2
    - cairo
    - fontconfig
  tags:
    - sudoforge.fonts

- name: Enable LCD filter
  file:
    src: "/etc/fonts/conf.avail/{{ item }}.conf"
    dest: "/etc/fonts/conf.d/{{ item }}.conf"
    state: link
  loop:
    - 11-lcdfilter-default
    - 10-sub-pixel-rgb
    - 10-hinting-slight
  tags:
    - sudoforge.fonts

- name: Push font substitutions
  copy:
    src: local.conf
    dest: /etc/fonts/local.conf
  tags:
    - sudoforge.fonts

- name: Install core fonts
  pacman:
    name: "{{ item }}"
    state: present
  loop:
      - terminus-font
      - cantarell-fonts
      - noto-fonts
      - ttf-dejavu
      - ttf-liberation
      - ttf-symbola
      - gsfonts
      - tex-gyre-fonts
      - ttf-droid
      - ttf-ubuntu-font-family
      - ttf-inconsolata
  tags:
    - sudoforge.fonts

- name: Install AUR fonts
  aur:
    name: "{{ item }}"
    user: "{{ sudoforge_aur_user }}"
    dbpath: "{{ sudoforge_aur_db_path }}"
    install: true
  loop:
    - ttf-signika
    - ttf-quintessential
    - ttf-oswald
    - ttf-opensans
    - ttf-merriweather-sans
    - ttf-merriweather
    - ttf-font-awesome-4
    - ttf-carlito
    - ttf-caladea
    - ttf-courier-prime
    - ttf-heuristica
  tags:
    - sudoforge.fonts
