---
- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - freetype2
    - cairo
    - fontconfig
  tags:
    - sudoforge.fonts

- name: Enable LCD filter
  file:
    src: "/etc/fonts/conf.avail/{{ item }}.conf"
    dest: "/etc/fonts/conf.d/{{ item }}.conf"
    state: link
  loop:
    - 11-lcdfilter-default
    - 10-sub-pixel-rgb
    - 10-hinting-slight
  tags:
    - sudoforge.fonts

- name: Push font substitutions
  copy:
    src: local.conf
    dest: /etc/fonts/local.conf
  tags:
    - sudoforge.fonts
